### PR TITLE
fix(linux): use home cache dir to avoid tmpfs→ext4 EINVAL on SDK install

### LINKED ISSUE #181: xtool setup fails on linux mint
## Description

Xtool setup fails on linux mint:
```
xtool setup
Logged in.
- Apple ID: *icloud.com
- Team ID: *
- Token expiry: *
Now generating the Darwin SDK.

Please download Xcode from http://developer.apple.com/download/all/?q=Xcode
and enter the path to the downloaded Xcode.xip.

Path to Xcode.xip: xcode_1.xip
[Downloading toolset] 100%
[Extracting XIP] 100%
[Installing SDKs] 100%
[Cleaning up]
[Finalizing SDKs]
- iPhoneOS26.1.sdk
- iPhoneSimulator26.1.sdk
- MacOSX26.1.sdk
[Writing metadata]
Error: Error Domain=NSCocoaErrorDomain Code=512 "(null)"UserInfo={NSUserStringVariant=["Copy"], NSSourceFilePathErrorKey=/tmp/sh.xtool/tmp-DarwinSDKBuild-B32EEDB5-F534-411D-8574-3C6B4778202D/DarwinSDKBuild/darwin.artifactbundle/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift_static/macosx/CxxStdlib.swiftmodule/arm64-apple-macos.swiftdoc, NSFilePath=/tmp/sh.xtool/tmp-DarwinSDKBuild-B32EEDB5-F534-411D-8574-3C6B4778202D/DarwinSDKBuild/darwin.artifactbundle/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift_static/macosx/CxxStdlib.swiftmodule/arm64-apple-macos.swiftdoc, NSDestinationFilePath=/home/<username>/.swiftpm/swift-sdks/darwin.artifactbundle/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift_static/macosx/CxxStdlib.swiftmodule/arm64-apple-macos.swiftdoc, NSURL=file:///tmp/sh.xtool/tmp-DarwinSDKBuild-B32EEDB5-F534-411D-8574-3C6B4778202D/DarwinSDKBuild/darwin.artifactbundle/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift_static/macosx/CxxStdlib.swiftmodule/arm64-apple-macos.swiftdoc, NSUnderlyingError=Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument"}
Error: exit(1)
```

## Environment

Host OS (macOS/Linux/WSL):
Linux Mint

Host OS version:
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=22.2
DISTRIB_CODENAME=zara
DISTRIB_DESCRIPTION="Linux Mint 22.2 Zara"
NAME="Linux Mint"
VERSION="22.2 (Zara)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 22.2"
VERSION_ID="22.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=zara
UBUNTU_CODENAME=noble

iOS device version:
iOS 26.1

Swift version:
Swift version 6.2.1 (swift-6.2.1-RELEASE)
Target: x86_64-unknown-linux-gnu

SDK version:
Error: Swift SDK with ID `darwin`, host triple x86_64-unknown-linux-gnu, and target triple arm64-apple-ios is not currently installed.

### PR DESCRIPTION
**Pull request by swapnilnakate7**
## Problem

`xtool setup` fails on Linux Mint (and other distros) with:

```
Error: Error Domain=NSCocoaErrorDomain Code=512 "(null)" UserInfo={
  NSUserStringVariant=["Copy"],
  NSSourceFilePathErrorKey=/tmp/sh.xtool/tmp-DarwinSDKBuild-.../darwin.artifactbundle/...,
  NSDestinationFilePath=/home/<user>/.swiftpm/swift-sdks/darwin.artifactbundle/...,
  NSUnderlyingError=Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument"
}
```

## Root Cause

On Linux Mint (and Ubuntu-based distros), `/tmp` is mounted as **tmpfs** while the home directory is on **ext4**. Foundation's `FileManager.copyItem` uses `sendfile(2)` internally, which returns `EINVAL (22)` when copying between different filesystem types.

`TemporaryDirectoryRoot` defaults to `FileManager.default.temporaryDirectory` → `/tmp` on Linux. When `swift sdk install` copies the built SDK from `/tmp/sh.xtool/...` to `~/.swiftpm/swift-sdks/`, it crosses filesystem boundaries and fails.

## Fix

On Linux, default the temp directory root to `$XDG_CACHE_HOME/xtool` (falling back to `~/.cache/xtool`) instead of `/tmp`. This keeps the build directory and install destination on the same filesystem, so the copy always succeeds.

- `$XTL_TMPDIR` and `$TMPDIR` overrides continue to work as before
- macOS behaviour is unchanged
- Follows XDG Base Directory Specification

## Changes

One file, `Sources/XUtils/TemporaryDirectory.swift` — 11 lines added inside a `#if os(Linux)` block.

Fixes #181

### CODE REVIEW

File: Sources/XUtils/TemporaryDirectory.swift [hunk 1]
```diff
@@ -70,7 +70,18 @@ private struct TemporaryDirectoryRoot {
...
+            // Using a cache dir on the home filesystem avoids the cross-fs copy entirely.
+            let xdgCache = env["XDG_CACHE_HOME"].map { URL(fileURLWithPath: $0) }
+                ?? FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".cache")
+            base = xdgCache.appendingPathComponent("xtool")
+            #else
             base = FileManager.default.temporaryDirectory
+            #endif
         }
 
         let url = base.appendingPathComponent("sh.xtool")
```
Comment (kabiroberai) [inline Sources/XUtils/TemporaryDirectory.swift]: can we avoid doing this in the branch you added, since the directory is already `~/.cache/xtool`? we can instead append `sh.xtool` specifically in the (XTL_)TMPDIR and macOS-temporaryDirectory branches.

**Review by kabiroberai — COMMENTED** [review]
thanks! looks good for the most part, just one nit

File: Sources/XUtils/TemporaryDirectory.swift (hunk 1 above)
Comment (swapnilnakate7) [reply Sources/XUtils/TemporaryDirectory.swift]: Good catch, fixed! Moved the `sh.xtool` append into the TMPDIR and macOS branches so the Linux path stays at `~/.cache/xtool` directly.

File: Sources/XUtils/TemporaryDirectory.swift [hunk 2]
```diff
@@ -68,12 +68,23 @@ private struct TemporaryDirectoryRoot {
...
+            let xdgCache = env["XDG_CACHE_HOME"].map { URL(fileURLWithPath: $0) }
+                ?? FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".cache")
+            base = xdgCache.appendingPathComponent("xtool")
+            #else
+            base = FileManager.default.temporaryDirectory.appendingPathComponent("sh.xtool")
+            #endif
         }
 
-        let url = base.appendingPathComponent("sh.xtool")
+        let url = base
```
Comment (kabiroberai) [inline Sources/XUtils/TemporaryDirectory.swift]: last nit, can we drop this and just rename base to url?

Comment (swapnilnakate7) [reply Sources/XUtils/TemporaryDirectory.swift]: Done, renamed `base` to `url` directly.

**Review by kabiroberai — APPROVED** [review]
